set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_ENV_PASSTHROUGH_UNTRACKED "_CL_")
set(VCPKG_C_FLAGS [=[/experimental:deterministic /pathmap:C:\=c/]=])
set(VCPKG_CXX_FLAGS [=[/experimental:deterministic /pathmap:C:\=c/]=])
set(VCPKG_LINKER_FLAGS "/Brepro /PDBALTPATH:%_PDB%")
